### ISSUE TITLE
DNAcopy

### ISSUE THREAD

**Issue by mpierrejean** [mpierrejean/jointseg#3]
If DNAcopy is not installed jointseg cannot be installed.

**Comment by pneuvial** [comment]
I've added 

    biocViews:

to the package `DESCRIPTION` (as per https://github.com/hadley/devtools/issues/700) so that R is aware of BioC packages. This seems to be a dirty hack though.

Commit: 2120060f982346c868d22cf1cb1c72b0c4b8c3f4
